---
  openapi: "3.0.1"
  info: 
    title: "TrainsAPI"
    version: "1.0.0"
  servers: 
    - 
      url: "/"
  security: 
    - 
      default: []
  paths: 
    /schedule/from/{departure}: 
      get: 
        parameters: 
          - 
            name: "departure"
            in: "path"
            required: true
            style: "simple"
            explode: false
            schema: 
              type: "string"
              format: "string"
        responses: 
          200: 
            description: "ok"
        security: 
          - 
            default: []
        x-auth-type: null
        x-throttling-tier: null
    /schedule/to/{arrival}: 
      get: 
        parameters: 
          - 
            name: "arrival"
            in: "path"
            required: true
            style: "simple"
            explode: false
            schema: 
              type: "string"
              format: "string"
        responses: 
          200: 
            description: "ok"
        security: 
          - 
            default: []
        x-auth-type: null
        x-throttling-tier: null
    /destinations: 
      get: 
        parameters: []
        responses: 
          200: 
            description: "ok"
        security: 
          - 
            default: []
        x-auth-type: null
        x-throttling-tier: null
  components: 
    securitySchemes: 
      default: 
        type: "oauth2"
        flows: 
          implicit: 
            authorizationUrl: "https://test.com"
            scopes: {}
  x-wso2-auth-header: "Authorization"
  x-throttling-tier: "Unlimited"
  x-wso2-cors: 
    corsConfigurationEnabled: false
    accessControlAllowOrigins: 
      - "*"
    accessControlAllowCredentials: false
    accessControlAllowHeaders: 
      - "authorization"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "SOAPAction"
    accessControlAllowMethods: 
      - "GET"
      - "PUT"
      - "POST"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
  x-wso2-production-endpoints: 
    urls: 
      - "http://localhost:3000"
    type: "http"
  x-wso2-sandbox-endpoints: 
    urls: 
      - "http://localhost:3000"
    type: "http"
  x-wso2-basePath: "/trains/1.0.0"
  x-wso2-transports: 
    - "http"
    - "https"
